### ISSUE TITLE
Uploaded file ends up as zero bytes

### ISSUE THREAD

**Issue by gabek** [ParticleApps/CloudAppSDK#1]
Not sure where to look deeper into this, but files uploaded end up as zero bytes on S3.

Possibly related: The slug that is generated seems really short, for example:
`http://f.gabe.bz/msf2`
But this might just be a side effect of some hash of the data, and since there's no data it ends up with a short slug.

Is there anything I can do to help fix this?

```
curl -v "https://d3vv6lp55qjaqc.cloudfront.net/items/0i0b3n2X2j133c2m3L0x/LongtailOnTV.jpg?X-CloudApp-Visitor-Id=47443"
...
< HTTP/2 200
< content-type: image/jpeg
< content-length: 0
< date: Wed, 04 Oct 2017 19:11:49 GMT
< last-modified: Wed, 04 Oct 2017 19:10:39 GMT
< etag: "d41d8cd98f00b204e9800998ecf8427e"
< x-amz-meta-slug: msf2
< accept-ranges: bytes
< server: AmazonS3
```

**Comment by Frostbitee08** [comment]
@gabek Uploading single files takes place here https://github.com/ParticleApps/CloudAppSDK/blob/master/CloudApp%20SDK/CAUploader.m. I just tested with a few JPGs and unfortunately was unable to replicate this. Uploading requires two requests outlined here: http://developer.getcloudapp.com/#add-item-upload-file

1.) Request a new file: This is a request made to CloudApp's server which creates an S3 endpoint for the file upload.

2.) S3 File Upload: Actually upload the file to S3.

My guess is that the first request finishes successfully, but the second request fails leaving you with an empty file on S3. Its possible that you did not have the proper permissions to read the file, or that the file was unable to be parsed by the multipart network request https://github.com/ParticleApps/CloudAppSDK/blob/master/CloudApp%20SDK/CANetworkManager.m#L213

**Comment by Frostbitee08** [comment]
@gabek I added a check for valid file paths here https://github.com/ParticleApps/CloudAppSDK/commit/747e76294586347d1e38a2119143179113541270

I prefer this to exiting. We already include failure blocks, we should utilize those instead.
